-- HomeMind schema v2: family memory.

CREATE TABLE IF NOT EXISTS homemind_family_memories (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  memory_id     TEXT NOT NULL UNIQUE,
  family_id     TEXT NOT NULL REFERENCES homemind_families(family_id) ON DELETE CASCADE,
  subject_type  TEXT NOT NULL,
  subject_id    TEXT,
  content       TEXT NOT NULL,
  memory_type   TEXT NOT NULL,
  importance    DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  confidence    DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  visibility    TEXT NOT NULL DEFAULT 'FAMILY',
  source_type   TEXT NOT NULL,
  source_id     TEXT,
  created_by    BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at    BIGINT NOT NULL,
  updated_at    BIGINT NOT NULL,
  expires_at    BIGINT,
  status        TEXT NOT NULL DEFAULT 'ACTIVE'
);

CREATE INDEX IF NOT EXISTS idx_homemind_family_memories_family
  ON homemind_family_memories(family_id, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_homemind_family_memories_subject
  ON homemind_family_memories(family_id, subject_type, subject_id);

UPDATE _homemind_schema_version SET version = 2;
