-- HomeMind schema v6: family invites.

CREATE TABLE IF NOT EXISTS homemind_family_invites (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invite_id      TEXT NOT NULL UNIQUE,
  family_id      TEXT NOT NULL REFERENCES homemind_families(family_id) ON DELETE CASCADE,
  role           TEXT NOT NULL DEFAULT 'MEMBER',
  display_name   TEXT NOT NULL,
  token_hash     TEXT NOT NULL UNIQUE,
  created_by     INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at     BIGINT NOT NULL,
  expires_at     BIGINT NOT NULL,
  redeemed_at    BIGINT,
  redeemed_by    INTEGER REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_homemind_family_invites_family
  ON homemind_family_invites(family_id, redeemed_at);

UPDATE _homemind_schema_version SET version = 6;
