-- HomeMind schema v10: persistent asset jobs (PostgreSQL).
--
-- Mirror of the SQLite migration. ``BIGSERIAL`` replaces ``INTEGER PRIMARY
-- KEY AUTOINCREMENT``, ``BIGINT`` replaces ``INTEGER`` for epoch columns,
-- and ``CREATE TABLE IF NOT EXISTS`` keeps the migration idempotent on
-- databases that recorded the version out of band.

CREATE TABLE IF NOT EXISTS homemind_asset_jobs (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id            TEXT NOT NULL UNIQUE,
  family_id         TEXT NOT NULL REFERENCES homemind_families(family_id) ON DELETE CASCADE,
  source_id         TEXT,
  job_type          TEXT NOT NULL,
  status            TEXT NOT NULL DEFAULT 'PENDING',
  cursor_json       TEXT NOT NULL DEFAULT '{}',
  total_items       INTEGER NOT NULL DEFAULT 0,
  processed_items   INTEGER NOT NULL DEFAULT 0,
  succeeded_items   INTEGER NOT NULL DEFAULT 0,
  skipped_items     INTEGER NOT NULL DEFAULT 0,
  failed_items      INTEGER NOT NULL DEFAULT 0,
  error_summary     TEXT,
  requested_by      BIGINT NOT NULL,
  created_at        BIGINT NOT NULL,
  started_at        BIGINT,
  updated_at        BIGINT NOT NULL,
  finished_at       BIGINT,
  lease_owner       TEXT,
  lease_expires_at  BIGINT
);

CREATE INDEX IF NOT EXISTS idx_homemind_asset_jobs_family
  ON homemind_asset_jobs(family_id, status, created_at);

CREATE INDEX IF NOT EXISTS idx_homemind_asset_jobs_claim
  ON homemind_asset_jobs(status, lease_expires_at, created_at);

CREATE TABLE IF NOT EXISTS homemind_asset_job_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id       TEXT NOT NULL UNIQUE,
  job_id        TEXT NOT NULL REFERENCES homemind_asset_jobs(job_id) ON DELETE CASCADE,
  asset_id      TEXT,
  source_path   TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'PENDING',
  attempt_count INTEGER NOT NULL DEFAULT 0,
  error         TEXT,
  created_at    BIGINT NOT NULL,
  updated_at    BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_homemind_asset_job_items_job
  ON homemind_asset_job_items(job_id, status, id);

CREATE INDEX IF NOT EXISTS idx_homemind_asset_job_items_retry
  ON homemind_asset_job_items(status, attempt_count);

UPDATE _homemind_schema_version SET version = 10;
