-- HomeMind schema v11: unified family search index + embedding metadata
-- (PostgreSQL).
--
-- Mirror of the SQLite migration, with three PostgreSQL-specific
-- pieces:
--
--   * ``to_tsvector('simple', text)`` instead of an FTS5 virtual
--     table. The ``simple`` configuration keeps every CJK character as
--     its own token without installing zhparser or ngram, matching the
--     behaviour the SQLite side gets from ``unicode61``.
--   * A GIN expression index over that tsvector.
--   * ``BYTEA`` for the raw embedding vector (SQLite stores BLOB).

CREATE TABLE IF NOT EXISTS homemind_search_documents (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id       TEXT NOT NULL UNIQUE,
  family_id         TEXT NOT NULL REFERENCES homemind_families(family_id) ON DELETE CASCADE,
  kind              TEXT NOT NULL,
  entity_id         TEXT NOT NULL,
  title             TEXT NOT NULL DEFAULT '',
  text              TEXT NOT NULL DEFAULT '',
  space_id          TEXT,
  owner_member_id   TEXT,
  visibility        TEXT NOT NULL DEFAULT 'FAMILY',
  status            TEXT NOT NULL DEFAULT 'ACTIVE',
  importance        DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  captured_at       BIGINT,
  updated_at        BIGINT NOT NULL,
  embedding_model        TEXT,
  embedding_dimensions   INTEGER,
  embedding_version      INTEGER,
  embedding_content_hash TEXT,
  embedding          BYTEA
);

CREATE INDEX IF NOT EXISTS idx_homemind_search_docs_scope
  ON homemind_search_documents(family_id, kind, visibility, status);

CREATE INDEX IF NOT EXISTS idx_homemind_search_docs_entity
  ON homemind_search_documents(family_id, entity_id);

CREATE INDEX IF NOT EXISTS idx_homemind_search_docs_recent
  ON homemind_search_documents(family_id, updated_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_homemind_search_docs_embedding
  ON homemind_search_documents(embedding_model, embedding_version, embedding_dimensions);

-- Keyword search.
--
-- ``pg_trgm`` rather than ``to_tsvector('simple', ...)``: the built-in
-- parser treats a run of CJK characters as one token, so a Chinese
-- substring query cannot match. Trigram indexes character triples and
-- handles Chinese, filenames, and free text uniformly, matching the
-- SQLite side exactly. ``simple_tsquery`` is only used as a secondary
-- ranking signal because it *is* good at whole-word matching for
-- languages that use spaces.
--
-- ``pg_trgm`` must be available; it ships with PostgreSQL contrib. The
-- index is created in its own statement so a database without the
-- extension fails at this migration rather than silently losing search.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX IF NOT EXISTS idx_homemind_search_docs_trgm
  ON homemind_search_documents
  USING GIN ((coalesce(text, '') || ' ' || coalesce(title, '')) gin_trgm_ops);

CREATE TABLE IF NOT EXISTS homemind_search_cursors (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cursor_key    TEXT NOT NULL UNIQUE,
  family_id     TEXT NOT NULL REFERENCES homemind_families(family_id) ON DELETE CASCADE,
  created_by    BIGINT NOT NULL,
  created_at    BIGINT NOT NULL,
  expires_at    BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_homemind_search_cursors_expiry
  ON homemind_search_cursors(expires_at);

UPDATE _homemind_schema_version SET version = 11;
