-- HomeMind schema v12: external processing + MCP call audit (PostgreSQL).
--
-- Mirror of the SQLite migration. One table serves two writers: the
-- MCP server logs a row per tool call, and the external-processing
-- guard logs a row per outbound provider call.

CREATE TABLE IF NOT EXISTS homemind_external_processing_audit (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  audit_id        TEXT NOT NULL UNIQUE,
  family_id       TEXT NOT NULL DEFAULT '',
  user_id         BIGINT NOT NULL,
  asset_id        TEXT,
  provider_id     TEXT NOT NULL,
  model           TEXT NOT NULL DEFAULT '',
  operation       TEXT NOT NULL,
  data_categories TEXT NOT NULL DEFAULT '[]',
  result          TEXT NOT NULL DEFAULT '{}',
  transaction_id  TEXT,
  created_at      BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_homemind_external_audit_family
  ON homemind_external_processing_audit(family_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_homemind_external_audit_asset
  ON homemind_external_processing_audit(asset_id);

CREATE INDEX IF NOT EXISTS idx_homemind_external_audit_user
  ON homemind_external_processing_audit(user_id, created_at DESC);

UPDATE _homemind_schema_version SET version = 12;
