-- HomeMind schema v13: family privacy settings + external provider policy
-- (PostgreSQL).
--
-- Mirror of the SQLite migration. ``BOOLEAN`` replaces the SQLite
-- ``INTEGER`` 0/1 flags.

CREATE TABLE IF NOT EXISTS homemind_family_privacy_settings (
  id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id                      TEXT NOT NULL UNIQUE REFERENCES homemind_families(family_id) ON DELETE CASCADE,
  processing_mode                TEXT NOT NULL DEFAULT 'ASK_EACH_TIME',
  allow_external_vision          BOOLEAN NOT NULL DEFAULT FALSE,
  allow_external_embedding       BOOLEAN NOT NULL DEFAULT FALSE,
  allow_external_geocoding       BOOLEAN NOT NULL DEFAULT FALSE,
  allow_sensitive_external       BOOLEAN NOT NULL DEFAULT FALSE,
  allowed_provider_ids           TEXT NOT NULL DEFAULT '[]',
  updated_at                     BIGINT NOT NULL,
  updated_by                     BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS homemind_external_processing_requests (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id        TEXT NOT NULL UNIQUE,
  family_id         TEXT NOT NULL REFERENCES homemind_families(family_id) ON DELETE CASCADE,
  asset_id          TEXT,
  user_id           BIGINT NOT NULL,
  operation         TEXT NOT NULL,
  provider_id       TEXT NOT NULL,
  model             TEXT NOT NULL DEFAULT '',
  data_categories   TEXT NOT NULL DEFAULT '[]',
  status            TEXT NOT NULL DEFAULT 'PENDING',
  decided_by        BIGINT,
  decided_at        BIGINT,
  transaction_id    TEXT,
  created_at        BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_homemind_external_requests_status
  ON homemind_external_processing_requests(family_id, status, created_at DESC);

UPDATE _homemind_schema_version SET version = 13;
