-- HomeMind schema v14: family export / import jobs (PostgreSQL).
--
-- Mirror of the SQLite migration.

CREATE TABLE IF NOT EXISTS homemind_family_exports (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  export_id             TEXT NOT NULL UNIQUE,
  family_id             TEXT NOT NULL REFERENCES homemind_families(family_id) ON DELETE CASCADE,
  status                TEXT NOT NULL DEFAULT 'PENDING',
  format_version        INTEGER NOT NULL DEFAULT 1,
  includes_original_assets BOOLEAN NOT NULL DEFAULT FALSE,
  manifest_json         TEXT NOT NULL DEFAULT '{}',
  file_path             TEXT,
  byte_size             BIGINT NOT NULL DEFAULT 0,
  checksum              TEXT,
  error_summary         TEXT,
  requested_by          BIGINT NOT NULL,
  created_at            BIGINT NOT NULL,
  started_at            BIGINT,
  finished_at           BIGINT,
  expires_at            BIGINT,
  lease_owner           TEXT,
  lease_expires_at      BIGINT
);

CREATE INDEX IF NOT EXISTS idx_homemind_family_exports_family
  ON homemind_family_exports(family_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_homemind_family_exports_expiry
  ON homemind_family_exports(expires_at);

CREATE TABLE IF NOT EXISTS homemind_family_imports (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_id       TEXT NOT NULL UNIQUE,
  target_family_id TEXT REFERENCES homemind_families(family_id) ON DELETE CASCADE,
  status          TEXT NOT NULL DEFAULT 'STAGED',
  manifest_json   TEXT NOT NULL DEFAULT '{}',
  dry_run         BOOLEAN NOT NULL DEFAULT TRUE,
  conflict_report TEXT NOT NULL DEFAULT '{}',
  error_summary   TEXT,
  requested_by    BIGINT NOT NULL,
  decided_by      BIGINT,
  decided_at      BIGINT,
  created_at      BIGINT NOT NULL,
  finished_at     BIGINT
);

CREATE INDEX IF NOT EXISTS idx_homemind_family_imports_target
  ON homemind_family_imports(target_family_id, status, created_at DESC);

UPDATE _homemind_schema_version SET version = 14;
