-- HomeMind schema v25: asynchronous device asset transfers
-- (PostgreSQL).
--
-- Mirror of the SQLite migration: one transfer row pinned to a single
-- (family, asset, device) triple, carrying the resource version the
-- device may resume against, plus short-lived hashed data-plane
-- credentials.

CREATE TABLE IF NOT EXISTS homemind_asset_transfers (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_id      TEXT NOT NULL UNIQUE,
  family_id        TEXT NOT NULL REFERENCES homemind_families(family_id) ON DELETE CASCADE,
  -- Intentionally NOT a foreign key: a transfer row is an audit record and
  -- must outlive the asset index entry it describes. See the SQLite migration.
  asset_id         TEXT NOT NULL,
  device_id        TEXT NOT NULL REFERENCES homemind_family_devices(device_id) ON DELETE CASCADE,
  request_key      TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'PENDING',
  source_kind      TEXT NOT NULL DEFAULT 'LOCAL_FILE',
  size_bytes       BIGINT NOT NULL,
  sha256           TEXT NOT NULL,
  source_mtime_ns  BIGINT,
  etag             TEXT NOT NULL,
  chunk_size       BIGINT NOT NULL,
  bytes_reported   BIGINT NOT NULL DEFAULT 0,
  last_progress_at BIGINT,
  expires_at       BIGINT NOT NULL,
  completed_at     BIGINT,
  failure_code     TEXT,
  failure_detail   TEXT,
  created_at       BIGINT NOT NULL,
  updated_at       BIGINT NOT NULL,
  UNIQUE(device_id, request_key),
  CONSTRAINT ck_homemind_asset_transfers_progress
    CHECK (bytes_reported >= 0 AND bytes_reported <= size_bytes)
);

CREATE INDEX IF NOT EXISTS idx_homemind_asset_transfers_device
  ON homemind_asset_transfers(device_id, status, created_at);

CREATE INDEX IF NOT EXISTS idx_homemind_asset_transfers_asset
  ON homemind_asset_transfers(family_id, asset_id, status);

CREATE INDEX IF NOT EXISTS idx_homemind_asset_transfers_expiry
  ON homemind_asset_transfers(status, expires_at);

CREATE TABLE IF NOT EXISTS homemind_asset_transfer_tokens (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_id     TEXT NOT NULL UNIQUE,
  transfer_id  TEXT NOT NULL REFERENCES homemind_asset_transfers(transfer_id) ON DELETE CASCADE,
  token_hash   TEXT NOT NULL,
  expires_at   BIGINT NOT NULL,
  revoked_at   BIGINT,
  created_at   BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_homemind_asset_transfer_tokens_transfer
  ON homemind_asset_transfer_tokens(transfer_id, revoked_at, expires_at);

CREATE INDEX IF NOT EXISTS idx_homemind_asset_transfer_tokens_hash
  ON homemind_asset_transfer_tokens(token_hash);

UPDATE _homemind_schema_version SET version = 25;