-- Schema v20: HomeMind family foundation.

CREATE TABLE IF NOT EXISTS families (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id      TEXT NOT NULL UNIQUE,
  name           TEXT NOT NULL,
  avatar         TEXT,
  owner_user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  timezone       TEXT NOT NULL,
  locale         TEXT NOT NULL,
  created_at     INTEGER NOT NULL,
  updated_at     INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_families_owner ON families(owner_user_id);

CREATE TABLE IF NOT EXISTS family_members (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id      TEXT NOT NULL UNIQUE,
  family_id      TEXT NOT NULL REFERENCES families(family_id) ON DELETE CASCADE,
  user_id        INTEGER REFERENCES users(id) ON DELETE SET NULL,
  display_name   TEXT NOT NULL,
  role           TEXT NOT NULL DEFAULT 'MEMBER',
  avatar         TEXT,
  birthday       TEXT,
  status         TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at     INTEGER NOT NULL,
  updated_at     INTEGER NOT NULL,
  UNIQUE(family_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_family_members_family ON family_members(family_id);

CREATE TABLE IF NOT EXISTS family_memberships (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  membership_id  TEXT NOT NULL UNIQUE,
  family_id      TEXT NOT NULL REFERENCES families(family_id) ON DELETE CASCADE,
  member_id      TEXT NOT NULL UNIQUE REFERENCES family_members(member_id) ON DELETE CASCADE,
  user_id        INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role           TEXT NOT NULL DEFAULT 'MEMBER',
  status         TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at     INTEGER NOT NULL,
  updated_at     INTEGER NOT NULL,
  UNIQUE(family_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_family_memberships_user ON family_memberships(user_id);

CREATE TABLE IF NOT EXISTS family_relationships (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relationship_id    TEXT NOT NULL UNIQUE,
  family_id          TEXT NOT NULL REFERENCES families(family_id) ON DELETE CASCADE,
  from_member_id     TEXT NOT NULL REFERENCES family_members(member_id) ON DELETE CASCADE,
  to_member_id       TEXT NOT NULL REFERENCES family_members(member_id) ON DELETE CASCADE,
  relationship_type  TEXT NOT NULL,
  created_at         INTEGER NOT NULL,
  updated_at         INTEGER NOT NULL,
  CHECK(from_member_id <> to_member_id),
  UNIQUE(family_id, from_member_id, to_member_id, relationship_type)
);
CREATE INDEX IF NOT EXISTS idx_family_relationships_family ON family_relationships(family_id);

CREATE TABLE IF NOT EXISTS family_spaces (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  space_id    TEXT NOT NULL UNIQUE,
  family_id   TEXT NOT NULL REFERENCES families(family_id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  space_type  TEXT NOT NULL,
  owner_member_id TEXT REFERENCES family_members(member_id) ON DELETE SET NULL,
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL,
  UNIQUE(family_id, name)
);
CREATE INDEX IF NOT EXISTS idx_family_spaces_family ON family_spaces(family_id);

CREATE TABLE IF NOT EXISTS family_permissions (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permission_id     TEXT NOT NULL UNIQUE,
  family_id         TEXT NOT NULL REFERENCES families(family_id) ON DELETE CASCADE,
  subject_member_id TEXT REFERENCES family_members(member_id) ON DELETE CASCADE,
  space_id          TEXT REFERENCES family_spaces(space_id) ON DELETE CASCADE,
  action            TEXT NOT NULL,
  effect            TEXT NOT NULL,
  expires_at        INTEGER,
  created_by        INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_family_permissions_family ON family_permissions(family_id);
CREATE INDEX IF NOT EXISTS idx_family_permissions_subject ON family_permissions(subject_member_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_family_permissions_rule
  ON family_permissions(
    family_id,
    COALESCE(subject_member_id, ''),
    COALESCE(space_id, ''),
    action
  );

UPDATE _schema_version SET version = 20;
